# Generated by Django 2.2.12 on 2021-11-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Purchase',
            fields=[
                ('purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField(auto_now=True)),
                ('brand', models.CharField(default='', max_length=35)),
                ('item_model', models.CharField(blank=True, max_length=50, null=True)),
                ('item_serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Vendor', models.CharField(default='', max_length=35)),
                ('warranty_period', models.CharField(default='', max_length=35)),
                ('item_location', models.CharField(default='', max_length=35)),
                ('purchase_qty', models.IntegerField()),
                ('rec_status', models.CharField(blank=True, default='Pending', max_length=15, null=True)),
                ('issue_status', models.CharField(blank=True, default='Not Issued', max_length=15, null=True)),
                ('price', models.IntegerField(default=0)),
                ('rec_qty', models.IntegerField(blank=True, default=1, null=True)),
                ('issue_qty', models.IntegerField(blank=True, default=1, null=True)),
                ('last_date_of_warranty', models.DateField(blank=True, default='2021-09-13', null=True)),
                ('warranty_period_warning', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='item_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='item_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_Stock',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=50)),
                ('item_model', models.CharField(blank=True, default=None, max_length=50)),
                ('Vendor', models.CharField(blank=True, default='Opening Stock', max_length=20)),
                ('capacity', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('item_location', models.CharField(default='', max_length=50)),
                ('issued', models.CharField(default='Not Issued', max_length=15)),
                ('qty', models.IntegerField()),
                ('issue_qty', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Req_Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionForm',
            fields=[
                ('req_number', models.AutoField(primary_key=True, serialize=False)),
                ('req_Date', models.DateField(auto_now=True)),
                ('user', models.CharField(default='', max_length=50)),
                ('department', models.CharField(default='', max_length=50)),
                ('item', models.CharField(default='', max_length=50)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.IntegerField(blank=True, default=1, null=True)),
                ('item_image', models.ImageField(blank=True, default='', upload_to='')),
                ('status', models.CharField(blank=True, default='Pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('second_contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('second_contact_person_number', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='warranty_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phn_no', models.CharField(blank=True, max_length=10)),
                ('outlook_email', models.CharField(blank=True, max_length=50)),
                ('gmail', models.CharField(blank=True, max_length=50)),
                ('departments', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Receiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receiving', models.DateField(auto_now=True)),
                ('Bill_No', models.CharField(max_length=20, unique=True)),
                ('rec_qty', models.IntegerField(blank=True, default=1, null=True)),
                ('purchase_price', models.IntegerField(default=0)),
                ('pur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.IT_Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='it_purchase',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.RequisitionForm'),
        ),
        migrations.CreateModel(
            name='Issued_to',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_of_issue', models.DateField(auto_now=True)),
                ('issue_qty', models.IntegerField(blank=True, default=1, null=True)),
                ('O_stock', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='file.Opening_Stock')),
                ('Users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.User_Master')),
                ('purchase', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='file.IT_Purchase')),
            ],
            options={
                'unique_together': {('O_stock', 'purchase', 'Users')},
            },
        ),
    ]
