# Generated by Django 3.2.9 on 2021-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20211111_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_master',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_master',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_master',
            name='number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
