# Generated by Django 3.2.9 on 2021-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20211112_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_to',
            name='item',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
